// @flow
interface Data {
  logOut: string,
  goToPantry: string,
  goToRecipes: string,
  addItem: string,
  deleteAllItems: string,
  deleteAllInCart: string,
  goHome: string,
  removeImage: string,
  addIngredient: string,
  addDirection: string,
  addRecipe: string,
  uncheckAll: string,
  showInputs: string,
  hideInputs: string,
  save: string,
  sortAlpha: string,
  sortAisle: string,
  cancel: string,
  clear: string,
  goToCompleted: string,
}

const buttonStrings: Data = {
  logOut: 'Log Out',
  goToPantry: 'Go to Pantry',
  goToRecipes: 'Go to Recipes',
  addItem: 'Add Item',
  deleteAllItems: 'Delete ALL Items',
  deleteAllInCart: 'Delete ALL in Cart',
  goHome: 'Go Home',
  removeImage: 'Remove Image',
  addIngredient: 'Add Ingredient',
  addDirection: 'Add Direction',
  addRecipe: 'Add Recipe',
  uncheckAll: 'Uncheck All',
  showInputs: 'Show Inputs',
  hideInputs: 'Hide Inputs',
  save: 'Save',
  sortAlpha: 'Sort Alpha',
  sortAisle: 'Sort Aisle',
  cancel: 'Cancel',
  clear: 'Clear',
  goToCompleted: 'Go to Completed',
};

export default buttonStrings;
